package renshou.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSemimanufacturesStock<M extends BaseSemimanufacturesStock<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setSemimanufacturesOutgoingId(java.lang.Integer semimanufacturesOutgoingId) {
		set("semimanufactures_outgoing_id", semimanufacturesOutgoingId);
		return (M)this;
	}

	public java.lang.Integer getSemimanufacturesOutgoingId() {
		return get("semimanufactures_outgoing_id");
	}

	public M setSemimanufacturesStockNum(java.math.BigDecimal semimanufacturesStockNum) {
		set("semimanufactures_stock_num", semimanufacturesStockNum);
		return (M)this;
	}

	public java.math.BigDecimal getSemimanufacturesStockNum() {
		return get("semimanufactures_stock_num");
	}

}
