package renshou.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseLeaseWarehouseIn<M extends BaseLeaseWarehouseIn<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setWarehouseInNo(java.lang.String warehouseInNo) {
		set("warehouse_in_no", warehouseInNo);
		return (M)this;
	}

	public java.lang.String getWarehouseInNo() {
		return get("warehouse_in_no");
	}

	public M setWarehouseInDate(java.util.Date warehouseInDate) {
		set("warehouse_in_date", warehouseInDate);
		return (M)this;
	}

	public java.util.Date getWarehouseInDate() {
		return get("warehouse_in_date");
	}

	public M setCustomer(java.lang.Integer customer) {
		set("customer", customer);
		return (M)this;
	}

	public java.lang.Integer getCustomer() {
		return get("customer");
	}

	public M setWarehouseId(java.lang.Integer warehouseId) {
		set("warehouse_id", warehouseId);
		return (M)this;
	}

	public java.lang.Integer getWarehouseId() {
		return get("warehouse_id");
	}

	public M setLocation(java.lang.String location) {
		set("location", location);
		return (M)this;
	}

	public java.lang.String getLocation() {
		return get("location");
	}

	public M setWarehouseInPerson(java.lang.String warehouseInPerson) {
		set("warehouse_in_person", warehouseInPerson);
		return (M)this;
	}

	public java.lang.String getWarehouseInPerson() {
		return get("warehouse_in_person");
	}

	public M setState(java.lang.Boolean state) {
		set("state", state);
		return (M)this;
	}

	public java.lang.Boolean getState() {
		return get("state");
	}

	public M setPricePerDay(java.math.BigDecimal pricePerDay) {
		set("price_per_day", pricePerDay);
		return (M)this;
	}

	public java.math.BigDecimal getPricePerDay() {
		return get("price_per_day");
	}

}
