package renshou.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseWarehouse<M extends BaseWarehouse<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setWarehouseName(java.lang.String warehouseName) {
		set("warehouse_name", warehouseName);
		return (M)this;
	}

	public java.lang.String getWarehouseName() {
		return get("warehouse_name");
	}

	public M setPosition(java.lang.String position) {
		set("position", position);
		return (M)this;
	}

	public java.lang.String getPosition() {
		return get("position");
	}

	public M setPid(java.lang.Integer pid) {
		set("pid", pid);
		return (M)this;
	}

	public java.lang.Integer getPid() {
		return get("pid");
	}

}
