package renshou.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCompanyContact<M extends BaseCompanyContact<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setCompanyId(java.lang.String companyId) {
		set("company_id", companyId);
		return (M)this;
	}

	public java.lang.String getCompanyId() {
		return get("company_id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}

	public java.lang.String getName() {
		return get("name");
	}

	public M setCallNum(java.lang.String callNum) {
		set("call_num", callNum);
		return (M)this;
	}

	public java.lang.String getCallNum() {
		return get("call_num");
	}

	public M setQQ(java.lang.String QQ) {
		set("QQ", QQ);
		return (M)this;
	}

	public java.lang.String getQQ() {
		return get("QQ");
	}

	public M setWechat(java.lang.String wechat) {
		set("wechat", wechat);
		return (M)this;
	}

	public java.lang.String getWechat() {
		return get("wechat");
	}

	public M setEMail(java.lang.String eMail) {
		set("e_mail", eMail);
		return (M)this;
	}

	public java.lang.String getEMail() {
		return get("e_mail");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

}
