package renshou.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCompany<M extends BaseCompany<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setCompanyName(java.lang.String companyName) {
		set("company_name", companyName);
		return (M)this;
	}

	public java.lang.String getCompanyName() {
		return get("company_name");
	}

	public M setCompanyAddress(java.lang.String companyAddress) {
		set("company_address", companyAddress);
		return (M)this;
	}

	public java.lang.String getCompanyAddress() {
		return get("company_address");
	}

}
