package renshou.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseFinishedProductStorage<M extends BaseFinishedProductStorage<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setStorageTime(java.util.Date storageTime) {
		set("storage_time", storageTime);
		return (M)this;
	}

	public java.util.Date getStorageTime() {
		return get("storage_time");
	}

	public M setStorageNumber(java.lang.String storageNumber) {
		set("storage_number", storageNumber);
		return (M)this;
	}

	public java.lang.String getStorageNumber() {
		return get("storage_number");
	}

	public M setTUserId(java.lang.Integer tUserId) {
		set("t_user_id", tUserId);
		return (M)this;
	}

	public java.lang.Integer getTUserId() {
		return get("t_user_id");
	}

	public M setState(java.lang.Boolean state) {
		set("state", state);
		return (M)this;
	}

	public java.lang.Boolean getState() {
		return get("state");
	}

}
