package renshou.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseLeaseWarehouseOut<M extends BaseLeaseWarehouseOut<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setWarehouseInNo(java.lang.String warehouseInNo) {
		set("warehouse_in_no", warehouseInNo);
		return (M)this;
	}

	public java.lang.String getWarehouseInNo() {
		return get("warehouse_in_no");
	}

	public M setWarehouseOutNo(java.lang.String warehouseOutNo) {
		set("warehouse_out_no", warehouseOutNo);
		return (M)this;
	}

	public java.lang.String getWarehouseOutNo() {
		return get("warehouse_out_no");
	}

	public M setWarehouseOutDate(java.util.Date warehouseOutDate) {
		set("warehouse_out_date", warehouseOutDate);
		return (M)this;
	}

	public java.util.Date getWarehouseOutDate() {
		return get("warehouse_out_date");
	}

	public M setWarehouseOutPerson(java.lang.String warehouseOutPerson) {
		set("warehouse_out_person", warehouseOutPerson);
		return (M)this;
	}

	public java.lang.String getWarehouseOutPerson() {
		return get("warehouse_out_person");
	}

	public M setState(java.lang.Boolean state) {
		set("state", state);
		return (M)this;
	}

	public java.lang.Boolean getState() {
		return get("state");
	}

	public M setOutCost(java.math.BigDecimal outCost) {
		set("out_cost", outCost);
		return (M)this;
	}

	public java.math.BigDecimal getOutCost() {
		return get("out_cost");
	}

}
