package renshou.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSemimanufacturesOutgoing<M extends BaseSemimanufacturesOutgoing<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setOutgoingTime(java.util.Date outgoingTime) {
		set("outgoing_time", outgoingTime);
		return (M)this;
	}

	public java.util.Date getOutgoingTime() {
		return get("outgoing_time");
	}

	public M setOutgoingNumber(java.lang.String outgoingNumber) {
		set("outgoing_number", outgoingNumber);
		return (M)this;
	}

	public java.lang.String getOutgoingNumber() {
		return get("outgoing_number");
	}

	public M setCompanyId(java.lang.Integer companyId) {
		set("company_id", companyId);
		return (M)this;
	}

	public java.lang.Integer getCompanyId() {
		return get("company_id");
	}

	public M setTUserId(java.lang.Integer tUserId) {
		set("t_user_id", tUserId);
		return (M)this;
	}

	public java.lang.Integer getTUserId() {
		return get("t_user_id");
	}

	public M setState(java.lang.Boolean state) {
		set("state", state);
		return (M)this;
	}

	public java.lang.Boolean getState() {
		return get("state");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

}
