package renshou.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseLeaseWarehouseInventory<M extends BaseLeaseWarehouseInventory<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setWarehouseInNo(java.lang.String warehouseInNo) {
		set("warehouse_in_no", warehouseInNo);
		return (M)this;
	}

	public java.lang.String getWarehouseInNo() {
		return get("warehouse_in_no");
	}

	public M setPricePerDay(java.math.BigDecimal pricePerDay) {
		set("price_per_day", pricePerDay);
		return (M)this;
	}

	public java.math.BigDecimal getPricePerDay() {
		return get("price_per_day");
	}

}
