package renshou.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseFinishedProduct<M extends BaseFinishedProduct<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setFinishedNumber(java.lang.String finishedNumber) {
		set("finished_number", finishedNumber);
		return (M)this;
	}

	public java.lang.String getFinishedNumber() {
		return get("finished_number");
	}

	public M setTradeName(java.lang.String tradeName) {
		set("trade_name", tradeName);
		return (M)this;
	}

	public java.lang.String getTradeName() {
		return get("trade_name");
	}

	public M setSpecifications(java.lang.String specifications) {
		set("specifications", specifications);
		return (M)this;
	}

	public java.lang.String getSpecifications() {
		return get("specifications");
	}

	public M setMeasurementUnit(java.lang.String measurementUnit) {
		set("measurement_unit", measurementUnit);
		return (M)this;
	}

	public java.lang.String getMeasurementUnit() {
		return get("measurement_unit");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

}
