package renshou.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseLeaseWarehouseInProduct<M extends BaseLeaseWarehouseInProduct<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setWarehouseInNo(java.lang.String warehouseInNo) {
		set("warehouse_in_no", warehouseInNo);
		return (M)this;
	}

	public java.lang.String getWarehouseInNo() {
		return get("warehouse_in_no");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}

	public java.lang.String getName() {
		return get("name");
	}

	public M setSpecification(java.lang.String specification) {
		set("specification", specification);
		return (M)this;
	}

	public java.lang.String getSpecification() {
		return get("specification");
	}

	public M setUnit(java.lang.String unit) {
		set("unit", unit);
		return (M)this;
	}

	public java.lang.String getUnit() {
		return get("unit");
	}

	public M setQuantity(java.math.BigDecimal quantity) {
		set("quantity", quantity);
		return (M)this;
	}

	public java.math.BigDecimal getQuantity() {
		return get("quantity");
	}

	public M setUnitPrice(java.math.BigDecimal unitPrice) {
		set("unit_price", unitPrice);
		return (M)this;
	}

	public java.math.BigDecimal getUnitPrice() {
		return get("unit_price");
	}

	public M setPricePerDay(java.math.BigDecimal pricePerDay) {
		set("price_per_day", pricePerDay);
		return (M)this;
	}

	public java.math.BigDecimal getPricePerDay() {
		return get("price_per_day");
	}

	public M setState(java.lang.Boolean state) {
		set("state", state);
		return (M)this;
	}

	public java.lang.Boolean getState() {
		return get("state");
	}

}
