package renshou.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseLeaseWarehouseOutProduct<M extends BaseLeaseWarehouseOutProduct<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setWarehouseOutNo(java.lang.String warehouseOutNo) {
		set("warehouse_out_no", warehouseOutNo);
		return (M)this;
	}

	public java.lang.String getWarehouseOutNo() {
		return get("warehouse_out_no");
	}

	public M setProductId(java.lang.Integer productId) {
		set("product_id", productId);
		return (M)this;
	}

	public java.lang.Integer getProductId() {
		return get("product_id");
	}

	public M setOutQuantity(java.math.BigDecimal outQuantity) {
		set("out_quantity", outQuantity);
		return (M)this;
	}

	public java.math.BigDecimal getOutQuantity() {
		return get("out_quantity");
	}

}
