package renshou.model;

import renshou.model.base.BaseCompanyContact;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CompanyContact extends BaseCompanyContact<CompanyContact> {
	public static final CompanyContact dao = new CompanyContact().dao();
}
