package renshou.model;

import renshou.model.base.BaseFinishedProductStorageDetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FinishedProductStorageDetail extends BaseFinishedProductStorageDetail<FinishedProductStorageDetail> {
	public static final FinishedProductStorageDetail dao = new FinishedProductStorageDetail().dao();
}
