package renshou.model;

import renshou.model.base.BaseFinishedProduct;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FinishedProduct extends BaseFinishedProduct<FinishedProduct> {
	public static final FinishedProduct dao = new FinishedProduct().dao();
}
