package renshou.model;

import renshou.model.base.BaseFinishedProductStorage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FinishedProductStorage extends BaseFinishedProductStorage<FinishedProductStorage> {
	public static final FinishedProductStorage dao = new FinishedProductStorage().dao();
}
