package renshou.model;

import renshou.model.base.BaseFinishedProductStockDetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FinishedProductStockDetail extends BaseFinishedProductStockDetail<FinishedProductStockDetail> {
	public static final FinishedProductStockDetail dao = new FinishedProductStockDetail().dao();
}
