package renshou.model;

import renshou.model.base.BaseFinishedProductOutgoingDetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FinishedProductOutgoingDetail extends BaseFinishedProductOutgoingDetail<FinishedProductOutgoingDetail> {
	public static final FinishedProductOutgoingDetail dao = new FinishedProductOutgoingDetail().dao();
}
