package renshou.model;

import renshou.model.base.BaseFinishedProductStock;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FinishedProductStock extends BaseFinishedProductStock<FinishedProductStock> {
	public static final FinishedProductStock dao = new FinishedProductStock().dao();
}
