package renshou.model;

import renshou.model.base.BaseFinishedProductOutgoing;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FinishedProductOutgoing extends BaseFinishedProductOutgoing<FinishedProductOutgoing> {
	public static final FinishedProductOutgoing dao = new FinishedProductOutgoing().dao();
}
