package renshou.model;

import renshou.model.base.BaseLeaseWarehouseOut;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LeaseWarehouseOut extends BaseLeaseWarehouseOut<LeaseWarehouseOut> {
	public static final LeaseWarehouseOut dao = new LeaseWarehouseOut().dao();
}
