package renshou.model;

import renshou.model.base.BaseLeaseWarehouseInventory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LeaseWarehouseInventory extends BaseLeaseWarehouseInventory<LeaseWarehouseInventory> {
	public static final LeaseWarehouseInventory dao = new LeaseWarehouseInventory().dao();
}
