package renshou.model;

import renshou.model.base.BaseLeaseWarehouseOutProduct;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LeaseWarehouseOutProduct extends BaseLeaseWarehouseOutProduct<LeaseWarehouseOutProduct> {
	public static final LeaseWarehouseOutProduct dao = new LeaseWarehouseOutProduct().dao();
}
