package renshou.model;

import renshou.model.base.BaseLeaseWarehouseInProduct;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LeaseWarehouseInProduct extends BaseLeaseWarehouseInProduct<LeaseWarehouseInProduct> {
	public static final LeaseWarehouseInProduct dao = new LeaseWarehouseInProduct().dao();
}
