package renshou.model;

import renshou.model.base.BaseLeaseWarehouseIn;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LeaseWarehouseIn extends BaseLeaseWarehouseIn<LeaseWarehouseIn> {
	public static final LeaseWarehouseIn dao = new LeaseWarehouseIn().dao();
}
