package renshou.model;

import renshou.model.base.BaseLeaseWarehouseInventoryProduct;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LeaseWarehouseInventoryProduct extends BaseLeaseWarehouseInventoryProduct<LeaseWarehouseInventoryProduct> {
	public static final LeaseWarehouseInventoryProduct dao = new LeaseWarehouseInventoryProduct().dao();
}
