package renshou.model;

import renshou.model.base.BaseSemimanufacturesStockDetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SemimanufacturesStockDetail extends BaseSemimanufacturesStockDetail<SemimanufacturesStockDetail> {
	public static final SemimanufacturesStockDetail dao = new SemimanufacturesStockDetail().dao();
}
