package renshou.model;

import renshou.model.base.BaseSemimanufacturesOutgoing;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SemimanufacturesOutgoing extends BaseSemimanufacturesOutgoing<SemimanufacturesOutgoing> {
	public static final SemimanufacturesOutgoing dao = new SemimanufacturesOutgoing().dao();
}
