package renshou.model;

import renshou.model.base.BaseSemimanufacturesStock;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SemimanufacturesStock extends BaseSemimanufacturesStock<SemimanufacturesStock> {
	public static final SemimanufacturesStock dao = new SemimanufacturesStock().dao();
}
