package renshou.model;

import renshou.model.base.BaseSemimanufactures;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Semimanufactures extends BaseSemimanufactures<Semimanufactures> {
	public static final Semimanufactures dao = new Semimanufactures().dao();
}
