package renshou.model;

import renshou.model.base.BaseSemimanufacturesStorageDetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SemimanufacturesStorageDetail extends BaseSemimanufacturesStorageDetail<SemimanufacturesStorageDetail> {
	public static final SemimanufacturesStorageDetail dao = new SemimanufacturesStorageDetail().dao();
}
