package renshou.model;

import renshou.model.base.BaseSemimanufacturesStorage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SemimanufacturesStorage extends BaseSemimanufacturesStorage<SemimanufacturesStorage> {
	public static final SemimanufacturesStorage dao = new SemimanufacturesStorage().dao();
}
