package renshou.model;

import renshou.model.base.BaseSemimanufacturesOutgoingDetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SemimanufacturesOutgoingDetail extends BaseSemimanufacturesOutgoingDetail<SemimanufacturesOutgoingDetail> {
	public static final SemimanufacturesOutgoingDetail dao = new SemimanufacturesOutgoingDetail().dao();
}
