package renshou.model;

import renshou.model.base.BaseWarehouse;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Warehouse extends BaseWarehouse<Warehouse> {
	public static final Warehouse dao = new Warehouse().dao();
}
